### ISSUE TITLE
About Huntercoin Core

### ISSUE THREAD

**Issue by verdulo** [chronokings/huntercoin#115]
I'm sorry for writing in wrong place, but could you allow reporting issues in repository https://github.com/chronokings/huntercore?

The problem with the new client is that there's too many references to Namecoin - so it tries to use the same catalog and registry entries as new Namecoin Core, and I cannot run them side-by-side.

**Comment by p3yot3** [comment]
Agreed. I even get a namecoin popup when I receive a payment, which is a little confusing/annoying.

**Comment by chronokings** [comment]
can you try now (see if you can report issues in the huntercore repo).
