### ISSUE TITLE
old wallet to new wallet. using samewallet.dat or importing privkeys

### ISSUE THREAD

**Issue by regtable** [chronokings/huntercoin#117]
sorry if this may seem trivial but i have 10k+ transactions that i had in the old (first) wallet prior to you moving over to the name coin/bitcoin client. all incoming and no outgoing transactions. when i search those addresses on the block explorer they say the address does not exist however i can import thos privkeys into the new huc client and then nothing shows. i understand it has been a while but i cameaccross an old hdd with the block data and a wallet.dat can you assist me on how to recover the funds from the old clients.
last client version i had was 1.4.0

**Comment by chimaera** [comment]
Hi.
are the txs moves? (name_updates)
do you have some example addresses?

**Comment by regtable** [comment]
Thanks for the reply as soon as I am back to keys I will copy over examples
from old client and new. It's odd as new client has minimal info on th rd

**Comment by regtable** [comment]
Player reg collected bounty
 501.84 
txid : c1c1568eee42c5b1a27f643f46fb20f863d94aabeb28561133717f9df4189d5a
i know these are good txs as i was playing frantically during the early days. and i 'had' a balance and was claiming rewards. now everything says generated but not accepted on 1.4.0 and on the new huntercore all txs except name changes are listed as 0.00
H9SdiJboBBAfSJtupDhi8ZMtbUkYWqbZf5
HLwEhfbevi5pECgoWmdTgSY42Nc2UDJy3p
both the arresses i had in huntercoin 1.4.0 i was able to a. import these into hunter core latest release and b use my old wallet.dat in huntercore newest release.
currently i am trying to sync both wallets side by side with the network see if one or the other gets coins in them if not once fully synced il do a repairwallet reindex and what ever else i can think to poke it with a stick!
pleas see attached picture for example
https://imgur.com/a/O0oNIy8 <-- link to pic of wallets showing same addresses

https://imgur.com/a/SW9lqda <-- pic of transnational discrepancies between wallet versions.

**Comment by chimaera** [comment]
are you able to get the block numbers or blockhashes?

how long does this go on for or was it just early on (first few days of launch?)

The reason I ask is because there was a major forking issue at this point in time, 
So you may have been on the wrong chain? (this would explain why they would not show up in the blockexplorer).

**Comment by domob1812** [comment]
I tried looking up `c1c1568eee42c5b1a27f643f46fb20f863d94aabeb28561133717f9df4189d5a` on my node (which has `-txindex`, so knows about all txids of the full chain), but could not find it.  I agree that this likely means you were on some fork.

That is further confirmed by your last post, which lists the tx as unconfirmed and `game_reward_orphan`.

Can you still start the old client (without connecting to the network)?  It would be interesting to see which blocks your transactions were originally confirmed in.

**Comment by regtable** [comment]
unfortunatly not i do not have the onld block data and all txs in wallet.dat have been re marked :-(

**Comment by regtable** [comment]
H9SdiJboBBAfSJtupDhi8ZMtbUkYWqbZf5 < this is my new address if you would like to send me a caoin so i can make a player. also to verify i am up to speed on right chain. also i will then host this block datat as a boot strap

**Comment by regtable** [comment]
👍 thanks anon tipper!
