### ISSUE TITLE
Qt unresponsive during network operations

### ISSUE THREAD

**Issue by extro24** [chronokings/huntercoin#6]
The client is unresponsive during network operations like "Flushing wallet.dat" and "askfor block".

Need to integrate QCoreApplication::processEvents() or something similar so that events can be interrupted to process user input.

Reference:
http://doc.qt.digia.com/qq/qq27-responsive-guis.html

**Comment by chronokings** [comment]
I believe this issue is mostly fixed,
but please open another issue if not
