### ISSUE TITLE
pending issue

### ISSUE THREAD

**Issue by MithrilMan** [chronokings/huntercoin#72]
ok, people reported pending transactions problem and i faced them right yesterday while i was playing

here facts:
- i was playing, i sent a name_update to move TWO of my hunters (generals both) but one of them got killed the next block, before transaction had confirmation
- one of my RPC call fails (i use gettransaction to see transaction status and confirmation, see ending note) saying that transaction wasn't available ("ok, no problem" I thought, that transaction isn't visible anymore because i've been killed)
- problem is that the other hunter (the alive one) didn't get confirmation neither, standing forever in a pending status
- from that point, i've had strange wallet behaviour (with other transaction getting pending forever)

now i've added a "Delete Transaction" in my client but that didn't sove the issue because you'll have to restart client and it's not guaranteed that the problem will be fixed

i think we have a problem here with incorrect transaction, could you check what happen when "gettransaction" try to get a transaction about a killed player with no confirmation (btw don't think the problem is there) and what happen if player is killed while he has pending moves?

don't know if the problem is only about RPC or even standard client is affected
I'll try to reproduce on testnet, anyway it seems to be an important issue to get fixed

P.S.
- note that my client store all pending operations in an inmemory list and check every game_state if those transaction are in pending (0 confirmation) or not, then if the transaction is confirmed i trigger some client actions depending on the type of the transaction (name_new, name_firstupdate or name_update) so i have to keep that inmemory list

to check their status i call gettransaction passing the tx id of the inmemory pending operation, this cause the RPC exception when i try to ask a transaction of a death player (it's fine, talking about code flow, because then i remove it from the list, but don't know how that exception cause some problem in the wallet/daemon)
(don't tell me to use name_pending for that because i still have to know when a transaction has been confirmed because i trigger some actions, so i need an inmemory list).

**Comment by chronokings** [comment]
is the pending issues now fixed?
